language: c


env:
  global:
    - PATH=/opt/mingw64/bin/:/opt/mingw32/bin/:$PATH


before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04 ./" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install mingw-x-binutils mingw-x-gcc
  - sudo apt-get --assume-yes install gcc-multilib g++-multilib make libudev-dev libreadline6-dev
  - sudo apt-get --assume-yes install cmake3
  - sudo apt-get --assume-yes install python-pip python-virtualenv
  - virtualenv ~/virtualenv/python2.7
  - source ~/virtualenv/python2.7/bin/activate
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - unset CC
  - ./.build.sh

