#! /bin/bash
/usr/bin/x86_64-w64-mingw32-g++.org $*
STATUS=$?
if [ $STATUS -ne 0 ]; then
	echo "*** WRAPPER Status: $STATUS"
	sync
	sudo sysctl -w vm.drop_caches=3
	sleep 1
	/usr/bin/x86_64-w64-mingw32-g++.org $*
	STATUS=$?
	echo "*** WRAPPER Status: $STATUS"
fi
exit $STATUS
