#! /bin/bash
echo "*** WRAPPER ***"
/usr/bin/x86_64-w64-mingw32-g++.org $*
STATUS=$?
echo "*** WRAPPER Status: $STATUS"
if [ $STATUS -ne 0 ]; then
	sleep 1
	/usr/bin/x86_64-w64-mingw32-g++.org $*
	STATUS=$?
	echo "*** WRAPPER Status: $STATUS"
fi
exit $STATUS
